import { Character } from "../../../../noname/library/element/index.js";

export default {
	//国战无双
	//神将
	gz_shen_zhaoyun: new Character({
		sex: "male",
		group: "shen",
		groupInGuozhan: "shu",
		hp: 2,
		maxHp: 2,
		skills: ["gz_juejing", "gz_longhun"],
	}),
	gz_shen_guanyu: new Character({
		sex: "male",
		group: "shen",
		groupInGuozhan: "shu",
		hp: 5,
		maxHp: 5,
		skills: ["gz_wushen", "gz_wuhun"],
	}),
	gz_shen_lvmeng: new Character({
		sex: "male",
		group: "shen",
		groupInGuozhan: "wu",
		hp: 3,
		maxHp: 3,
		skills: ["gz_shelie", "gz_gongxin"],
	}),
	gz_shen_lvbu: new Character({
		sex: "male",
		group: "shen",
		groupInGuozhan: "qun",
		hp: 5,
		maxHp: 5,
		skills: ["gz_wuqian", "gz_shenfen"],
	}),
	gz_shen_caocao: new Character({
		sex: "male",
		group: "shen",
		groupInGuozhan: "wei",
		hp: 3,
		maxHp: 3,
		skills: ["gz_guixin", "gz_feiying"],
	}),
	gz_shen_zhouyu: new Character({
		sex: "male",
		group: "shen",
		groupInGuozhan: "wu",
		hp: 4,
		maxHp: 4,
		skills: ["gz_qinyin", "gz_yeyan"],
	}),
	gz_shen_simayi: new Character({
		sex: "male",
		group: "shen",
		groupInGuozhan: "wei",
		hp: 4,
		maxHp: 4,
		skills: ["gz_jilve", "gz_lianpo"],
		tempname: ["new_simayi", "xin_simayi"],
		names: "司马|懿",
	}),
	gz_shen_luxun: new Character({
		sex: "male",
		group: "shen",
		groupInGuozhan: "wu",
		hp: 4,
		maxHp: 4,
		skills: ["gz_junlve", "gz_cuike", "gz_zhanhuo"],
	}),
	gz_shen_ganning: new Character({
		sex: "male",
		group: "shen",
		groupInGuozhan: "wu",
		hp: 4,
		maxHp: 4,
		skills: ["gz_poxi", "gz_gn_jieying"],
	}),
	gz_shen_zhangliao: new Character({
		sex: "male",
		group: "shen",
		groupInGuozhan: "wei",
		hp: 4,
		maxHp: 4,
		skills: ["gz_duorui", "gz_zhiti"],
	}),
	gz_shen_liubei: new Character({
		sex: "male",
		group: "shen",
		groupInGuozhan: "shu",
		hp: 6,
		maxHp: 6,
		skills: ["gz_longnu", "gz_jieying"],
	}),
	gz_shen_zhugeliang: new Character({
		sex: "male",
		group: "shen",
		groupInGuozhan: "shu",
		hp: 3,
		maxHp: 3,
		skills: ["gz_qixing", "gz_kuangfeng", "gz_dawu"],
	}),
	//野心家
	gz_zhugedan: new Character({
		sex: "male",
		group: "ye",
		hp: 4,
		maxHp: 4,
		skills: ["gz_gongao"],
	}),
	gz_pot_weiyan: new Character({
		sex: "male",
		group: "ye",
		hp: 4,
		maxHp: 4,
		skills: ["gz_new_kuanggu"],
	}),
	gz_sb_lvbu: new Character({
		sex: "male",
		group: "ye",
		hp: 5,
		maxHp: 5,
		skills: ["gz_wuchang", "gz_liyu"],
	}),
	gz_yl_yuanshu: new Character({
		sex: "male",
		group: "ye",
		hp: 3,
		maxHp: 3,
		skills: ["gz_new_yongsi", "gz_new_weidi"],
	}),
	gz_jsrg_liuyan: new Character({
		sex: "male",
		group: "ye",
		hp: 3,
		maxHp: 3,
		skills: ["gz_tushe", "gz_limu"],
	}),
	//双势力文鸯
	gz_yangwan: new Character({
		sex: "female",
		group: "shu",
		hp: 3,
		maxHp: 3,
		skills: ["gzyouyan", "gzzhuihuan"],
		hasSkinInGuozhan: true,
	}),
	//阴的没边了十头人
	gz_shichangshi: new Character({
		sex: "male",
		group: "qun",
		hp: 2,
		maxHp: 2,
		skills: ["gz_danggu", "gz_mowang"],
		trashBin: ["sex:male_castrated"],
		names: "张|让-赵|忠-孙|璋-毕|岚-夏|恽-韩|悝-栗|嵩-段|珪-郭|胜-高|望",
	}),
	gz_scs_zhangrang: new Character({
		sex: "male",
		group: "qun",
		hp: 1,
		maxHp: 1,
		isUnseen: true,
		skills: ["gz_taoluan"],
		trashBin: ["sex:male_castrated"],
	}),
	gz_scs_zhaozhong: new Character({
		sex: "male",
		group: "qun",
		hp: 1,
		maxHp: 1,
		isUnseen: true,
		skills: ["gz_chiyan"],
		trashBin: ["sex:male_castrated"],
	}),
	gz_scs_sunzhang: new Character({
		sex: "male",
		group: "qun",
		hp: 1,
		maxHp: 1,
		isUnseen: true,
		skills: ["gz_zimou"],
		trashBin: ["sex:male_castrated"],
	}),
	gz_scs_bilan: new Character({
		sex: "male",
		group: "qun",
		hp: 1,
		maxHp: 1,
		isUnseen: true,
		skills: ["gz_picai"],
		trashBin: ["sex:male_castrated"],
	}),
	gz_scs_xiayun: new Character({
		sex: "male",
		group: "qun",
		hp: 1,
		maxHp: 1,
		isUnseen: true,
		skills: ["gz_yaozhuo"],
		trashBin: ["sex:male_castrated"],
	}),
	gz_scs_hankui: new Character({
		sex: "male",
		group: "qun",
		hp: 1,
		maxHp: 1,
		isUnseen: true,
		skills: ["gz_xiaolu"],
		trashBin: ["sex:male_castrated"],
	}),
	gz_scs_lisong: new Character({
		sex: "male",
		group: "qun",
		hp: 1,
		maxHp: 1,
		isUnseen: true,
		skills: ["gz_kuiji"],
		trashBin: ["sex:male_castrated"],
	}),
	gz_scs_duangui: new Character({
		sex: "male",
		group: "qun",
		hp: 1,
		maxHp: 1,
		isUnseen: true,
		skills: ["gz_chihe"],
		trashBin: ["sex:male_castrated"],
	}),
	gz_scs_guosheng: new Character({
		sex: "male",
		group: "qun",
		hp: 1,
		maxHp: 1,
		isUnseen: true,
		skills: ["gz_niqu"],
		trashBin: ["sex:male_castrated"],
	}),
	gz_scs_gaowang: new Character({
		sex: "male",
		group: "qun",
		hp: 1,
		maxHp: 1,
		isUnseen: true,
		skills: ["gz_miaoyu"],
		trashBin: ["sex:male_castrated"],
	}),
	gz_gaolan: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		skills: ["gz_jungong", "gz_dengli"],
		dieAudios: ["sp_gaolan"],
	}),
	gz_caoang: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		skills: ["kaikang"],
	}),
	gz_zhangxingcai: new Character({
		sex: "female",
		group: "shu",
		hp: 3,
		maxHp: 3,
		skills: ["shenxian", "gz_qiangwu"],
	}),
	gz_luzhi: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		skills: ["gz_qingzhong", "gz_weijing"],
	}),
	gz_quyi: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		skills: ["fuqi", "jiaozi"],
	}),
	gz_ws_caoying: new Character({
		sex: "female",
		group: "wei",
		hp: 4,
		maxHp: 4,
		skills: ["gz_lingren", "gz_fujian"],
		tempname: ["caoying"],
		dieAudios: ["caoying"],
		hasSkinInGuozhan: true,
	}),
	gz_ws_guansuo: new Character({
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		skills: ["gz_zhengnan"],
		tempname: ["guansuo"],
		dieAudios: ["guansuo"],
		hasSkinInGuozhan: true,
	}),
	gz_zhangxuan: new Character({
		sex: "female",
		group: "wu",
		hp: 4,
		maxHp: 4,
		skills: ["gz_tongli", "gz_shezang"],
	}),
	gz_zhangyao: new Character({
		sex: "female",
		group: "wu",
		hp: 4,
		maxHp: 4,
		skills: ["gz_yuanyu", "gz_xiyan"],
	}),
	gz_guanyinping: new Character({
		sex: "female",
		group: "shu",
		hp: 3,
		maxHp: 3,
		skills: ["xueji", "gz_huxiao"],
	}),
	gz_xinxianying: new Character({
		sex: "female",
		group: "wei",
		hp: 3,
		maxHp: 3,
		skills: ["gz_caishi"],
	}),
	gz_yj_zhanghe: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		skills: ["gz_zhilve"],
	}),
	gz_mizhu: new Character({
		sex: "male",
		group: "shu",
		hp: 3,
		maxHp: 3,
		skills: ["gz_ziyuan", "gz_jugu"],
	}),
	gz_caochun: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		skills: ["gz_shanjia"],
	}),
};

export const intro = {};

export const sort = "guozhan_shi";