export default {
	//yj_puyuan: "",
	//yao_yuanshu: "",
	yj_fazheng: "弹铗待试",
	//yj_hanbing: "",
	//yj_tengjia: "",
	yj_zhanghe: "宁国中郎将",
	yj_zhangliao: "蹈锋饮血",
	yj_xuhuang: "沉详性严",
	yj_ganning: "铃震没羽",
	kebineng: "瀚海鲸波",
	zhugeshang: "尚节殉义",
	liwan: "遐雁归迩",
	yj_sufei: "义荐恩还",
	yj_qiaozhou: "谶星沉祚",
	lukai: "青辞宰辅",
	yj_zhoubuyi: "稚雀清声",
	yj_weiyan: "骜勇孤战",
	yj_huangzhong: "强挚烈弓",
	hanlong: "冯河易水",
	wuanguo: "虎口折腕",
	sunli: "百炼公才",
	xiahoumao: "束甲之鸟",
	chenshi: "裨将可期",
	feiyao: "后将军",
	linghuyu: "名愚性浚",
	yj_simafu: "仁孝忠德",
	yj_xuangongzhu: "高陵翩蝶",
	xukun: "平虏击逆",
	xunyuxunyou: "谋定天下",
	yj_sb_guojia: "翼谋奇佐",
	mp_liuling: "醉侯",
	mp_wangrong: "间竹觅幽", //暂且未拥有正式称号,本称号取自武将制图作品
	yj_majun: "名巧天下",
	mp_xiangxiu: "出尘窥冥", //暂且未拥有正式称号,本称号取自武将制图作品
	new_yj_dongzhuo: "破羌安边",
	fj_peixiu: "玄静守真",
	wufu: "忠虹贯日",
	yj_zhanghuan: "正身洁己",
	yj_zhangyan: "黑山飞燕",
	v_sunce: "勇冠三江势",
	yj_y_xunxu: "博律明识",
	yj_x_xunxu: "博律明识",
};
