const characters = {
	tw_dm_zhouyu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["twjuyan", "twlihuo", "yingjian", "yiran"],
	},
	ol_re_nianshou: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olsuizhong", "olnianyi", "dchuace", "olfuyou"],
	},
	ol_le_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["oljiangwu", "olxinghan"],
		names: "诸葛|亮",
	},
	meituizhishen: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["dcshentui", "dcxurui"],
		names: "null|null",
	},
	gongbaiwan: {
		sex: "female",
		group: "qun",
		hp: 4,
		skills: ["dchaoshi"],
	},
	nizhuanzhishen: {
		sex: "male",
		group: "shen",
		hp: 4,
		maxHp: 5,
		skills: ["dcfanzhuan", "dcniyun"],
		names: "null|null",
	},
	shuimianzhishen: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["dckeshui"],
		names: "null|null",
	},
	bianhuanzhishen: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["dcbaibian"],
		names: "null|null",
	},
	juezezhishen: {
		sex: "female",
		group: "shen",
		hp: 4,
		skills: ["dchuibian"],
		names: "null|null",
	},
	weiquzhishen: {
		sex: "female",
		group: "shen",
		hp: 3,
		skills: ["dcweiqu"],
		names: "null|null",
	},
	keaizhishen: {
		sex: "female",
		group: "shen",
		hp: 3,
		skills: ["dcmaimeng"],
		names: "null|null",
	},
	tizhongzhishen: {
		sex: "female",
		group: "shen",
		hp: 5,
		skills: ["dcgunyuan", "dczuandai"],
		names: "null|null",
	},
	mb_chitu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["mbjunkui", "mbchiyuan"],
	},
	mb_jueying: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["mbjiguan", "mbzhengpeng"],
	},
	mb_dilu: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["mbjiguan", "mbyuetan"],
	},
	mb_muniu: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["mbshezi", "mbyixing"],
	},
	jm_yuanshu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["mbjimi", "mbmaodie"],
	},
	tw_dm_quyi: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["retieji", "dmchongqi", "dmfanquan"],
	},
	ol_le_caohong: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["olmojin", "oldingbao"],
	},
	ol_le_liushan: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["oltuoquan", "olxianglv", "olanle", "oldianzan"],
	},
	you_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["dcyingyou"],
	},
	bigsb_dengai: {
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 5,
		skills: ["olandu", "olqiqi"],
	},
	wild_liru: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olhuaquan", "olsanou"],
	},
	ren_jiangwei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["renhuoluan", "renguxing"],
	},
	ren_dengai: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["renneyan", "renqianyao"],
	},
	strong_caochong: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["strongduanti", "stronglianwu", "olchengxiang"],
	},
	taipingsangong: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["oltiangong", "oldigong", "olrengong"],
		names: "张|角-张|宝-张|梁",
	},
	yuanshaoyuanshu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["dclieti", "dcshigong", "dcluankui"],
		names: "袁|绍-袁|术",
	},
	tianji: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dcweiji", "dcsaima"],
	},
	ol_xiahouen: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["olyinfeng", "olfulu"],
		names: "夏侯|恩",
	},
	hanshiwuhu: {
		sex: "male",
		group: "wei",
		hp: 5,
		skills: ["oljuejue", "olpimi"],
		initFilters: ["noZhuHp"],
		names: "韩|德‌-韩|瑛-韩|瑶-韩|琼-韩|琪",
	},
	shi_cenhun: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["dcxinggong", "dcbaoshi"],
		names: "岑|昏",
	},
	ol_zishu: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["olzishu"],
	},
	ol_chouniu: {
		sex: "male",
		group: "qun",
		hp: 1,
		maxHp: 5,
		skills: ["olchouniu"],
	},
	ol_yinhu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olyinhu"],
	},
	ol_maotu: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["olmaotu"],
	},
	ol_chenlong: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olchenlong"],
	},
	ol_sishe: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["olsishe"],
	},
	ol_wuma: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olwuma"],
	},
	ol_weiyang: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["olweiyang"],
	},
	ol_shenhou: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["olshenhou"],
	},
	ol_youji: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["olyouji"],
	},
	ol_xugou: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olxugou"],
	},
	ol_haizhu: {
		sex: "male",
		group: "qun",
		hp: 5,
		skills: ["olhaizhu"],
	},
	ol_nianshou: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["olsuichong", "olshouhun"],
	},
	ol_jsrg_lvbu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olfengzhu", "olyuyu", "ollbzhiji", "oljiejiu"],
		img: "image/character/jsrg_lvbu.jpg",
		names: "吕|布",
	},
	weiqing: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dcbeijin"],
	},
	liuxiecaojie: {
		sex: "male",
		group: "qun",
		hp: 2,
		skills: ["dcjuanlv", "dcqixin"],
		names: "刘|协-曹|节",
	},
	dc_zhaoyun: {
		sex: "male",
		group: "shen",
		hp: 1,
		skills: ["boss_juejing", "dclonghun", "dczhanjiang"],
		groupInGuozhan: "shu",
		initFilters: ["noZhuHp", "noZhuSkill"],
	},
	dc_sunce: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["dcshuangbi"],
	},
	nezha: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dcsantou", "dcfaqi"],
		initFilters: ["noZhuHp"],
		names: "李|哪吒",
	},
	dc_caocao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["dcjianxiong"],
	},
	dc_liubei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["dcrende"],
	},
	dc_sunquan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["dczhiheng"],
	},
	zhutiexiong: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dcbianzhuang"],
		dieAudios: ["2"],
	},
	xiaoyuehankehan: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dctongliao", "dcwudao"],
		dieAudios: ["3"],
		names: "null|null",
	},
	libai: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dclbjiuxian", "dcshixian"],
		dieAudios: ["2"],
	},
	sunwukong: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dcjinjing", "dccibei", "dcruyi"],
	},
	longwang: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dclonggong", "dcsitian"],
		names: "敖|广",
	},
	taoshen: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dcnutao"],
		names: "伍|子胥",
	},
	sunyang: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["clbshuijian"],
	},
	yeshiwen: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["clbjisu", "clbshuiyong"],
	},
	sp_jiben: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["spduanzhi", "spduyi"],
	},
	sp_fuhuanghou: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["spcangni", "spmixin"],
	},
	sp_fuwan: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["spfengyin", "spchizhong"],
	},
	old_lingju: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["jieyuan", "fenxin_old"],
		names: "吕|null",
	},
	sp_mushun: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["moukui"],
	},
	dc_wuyi: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["dcbenxi"],
		clans: ["陈留吴氏"],
	},
	quyuan: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dcqiusuo", "dclisao"],
		names: "芈|原",
	},
	xin_sunquan: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["dchuiwan", "dchuanli"],
	},
	wuhujiang: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["olhuyi"],
		names: "关|羽-张|飞-赵|云-马|超-黄|忠",
		dieAudios: ["5"],
	},
	dc_noname: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["dcchushan"],
		names: "null|null",
	},
	ol_jsrg_caocao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["oldingxi", "olnengchen", "olhuojie"],
		img: "image/character/jsrg_caocao.jpg",
	},
	jiangziya: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["xingzhou", "lieshen"],
		names: "姜|尚",
	},
	shengongbao: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["zhuzhou", "yaoxian"],
	},
	nanjixianweng: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["xwshoufa", "fuzhao"],
		names: "null|null",
	},
	bozai: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["quanjia"],
		names: "耄|耋",
	},
	xiangjiaoduanwu: {
		sex: "female",
		group: "qun",
		hp: 4,
		skills: ["xuyuan", "xiaomian"],
		names: "耄|耋",
	},
};

export default characters;
