export default {
	sxrm_zhouyu: "哀弦万耳惊",
	sxrm_sunshangxiang: "生死相随",
	sxrm_zhangzhao: "迂儒",
	sxrm_lusu: "养虺成蛇",
	sxrm_chen_caocao: "铜雀囚凰",
	sxrm_zhugeliang: "人也神也",
	sxrm_jiahua: "拔剑四顾",
	sxrm_zhaoyun: "坐收渔利",
	sxrm_caoren: "坚壳之蚌",

	sxrm_guanyu: "四海仰鼻息",
	sxrm_guanyinping: "天骄虎女",
	sxrm_yujin: "立地成佛",
	sxrm_mifang: "负荆之臣",
	sxrm_liufeng: "不动如山",
	sxrm_luxun: "孺子为将",
	sxrm_lvmeng: "病入膏肓",
	sxrm_pangde: "狂徒",
	sxrm_yanwen: "土鸡瓦犬",

	sxrm_caocao: "一目窥九州",
	sxrm_liubei: "潜隐波涛",
	sxrm_jianggan: "舌锁千帆",
	sxrm_huatuo: "上医医国",
	sxrm_lvboshe: "碧血东流",
	sxrm_fuhuanghou: "白绫蔽月",
	sxrm_xunyu: "末路见疑",
	sxrm_caopi: "兄友弟恭",
	sxrm_wanghou: "一刀斩讫",
};
