const voices = {
	"#sxrmqingjun1": "小阿瞒，叔父今天定要好好招待你。",
	"#sxrmqingjun2": "厨刀利、镬釜沸，烹猪宰羊，待老夫打酒而归！嘿嘿嘿！",
	"#sxrm_lvboshe:die": "我未尽地主之谊，小阿瞒何故急行？啊！",
	"#sxrmchengbian1": "待吾腾于九天，必与公一争天下。",
	"#sxrmchengbian2": "备有不挠之志，岂甘为公所讥。",
	"#sxrm_liubei:die": "公早已知备，今又何故再疑。",
	"#sxrmmitu1": "宫闱密密谋，暗室窃窃语。",
	"#sxrmmitu2": "此贼如若不死，父亲如何执掌朝堂。",
	"#sxrmqianliu1": "汝可匿于朝堂，待时而起之。",
	"#sxrmqianliu2": "朝野暗流渐起，曹贼如何得脱？",
	"#sxrm_fuhuanghou:die": "曹贼疑心甚重…甚重……",
	"#sxrmmiehai1": "吾欲知天下之疾，当从权臣始。",
	"#sxrmmiehai2": "吾有一法，可绝丞相百般疾痛。",
	"#sxrm_huatuo:die": "疑患不除，汝无药可医。",
	"#sxrmkuxin1": "万山终尽，万水终竭，万世青史，终付北邙! ",
	"#sxrmkuxin2": "念孤少时亦以壮心入世，而今空余此枯心。",
	"#sxrmsigu1": "叹诸君先孤而死，然孤先诸君而凋……",
	"#sxrmsigu2": "往昔逝者如斯，梦里纷至沓来! ",
	"#zhichi_sxrm_caocao1": "昔孤以不疑待公台，故招无妄之祸。",
	"#reganglie_sxrm_caocao1": "元让若终无愧于孤，何须窃汉官之嫌？",
	"#refankui_sxrm_caocao1": "孤尝梦三马同槽而食之，仲达可解何意？",
	"#reyiji_sxrm_caocao1": "奉孝之计，成则成矣，败则孤万劫不复！",
	"#oljieming_sxrm_caocao1": "孤与文若同路而来，奈何君竟弃孤先去！",
	"#fangzhu_sxrm_caocao1": "子桓恒以伪心对孤，孤知此亦为诚也！",
	"#shibei_sxrm_caocao1": "公与徒言尽忠于北，不过垂死以搏孤怜耳！",
	"#rechengxiang_sxrm_caocao1": "仓舒尚幼便破衣蔽孤，及长又将何为？",
	"#zhiyu_sxrm_caocao1": "公达与孤帐中秘策，岂欲传之后世？",
	"#jilei_sxrm_caocao1": "德祖欲假孤以显其才，孤岂会令之如愿？",
	"#benyu_sxrm_caocao1": "仲德有捧日之兆，能成大业，何甘屈身事孤？",
	"#chouce_sxrm_caocao1": "志才许孤山河功业，然竟殒身负孤！",
	"#wuhun_sxrm_caocao1": "孤独不疑云长之忠义，只恨公忠不在孤！",
	"#sxrm_caocao:die": "吾尝疑有生之荣，未尝疑有死之哀……",
};
export default voices;
