const characterSort = {
	extra_offline: ["shen_jiaxu", "shen_diaochan", "boss_zhaoyun", "le_shen_jiaxu", "ps_shen_machao", "mark_shen_machao", "zc26_shen_huangyueying", "sm_shen_machao", "sp_sm_shen_machao"],
	offline_scl: ["scl_lvbu", "scl_pangdegong", "scl_sunhanhua", "scl_miheng", "scl_peixiu", "scl_caoying", "scl_luotong", "scl_jiaxu"],
	offline_star: ["jsp_ganfuren", "sp_xiahoushi", "jsp_zhaoyun", "huangjinleishi", "sp_pangtong", "sp_daqiao", "sp_ganning", "sp_xiahoudun", "sp_lvmeng", "sp_zhangfei", "sp_liubei", "old_machao", "zhangliang", "jsp_caoren"],
	offline_sticker: ["sp_gongsunzan", "sp_simazhao", "sp_wangyuanji", "sp_xinxianying", "sp_liuxie"],
	offline_yijiang: ["ol_manchong", "ol_xinxianying", "ol_liuyu", "ol_zhangrang"],
	offline_luanwu: ["ns_lijue", "ns_zhangji", "ns_fanchou"],
	offline_yongjian: ["ns_chendao", "yj_caoang", "yj_caocao", "yj_liru", "yj_caohong", "yj_zhangfei", "yongjian_ganning", "yj_dongzhuo", "yj_xuyou", "yj_jiaxu", "yj_zhenji"],
	offline_piracyE_zy: ["pe_wangyun", "pe_zhonghui", "pe_sunchen", "pe_mengda", "pe_wenqin", "ns_caoanmin", "jiangqing", "kongrong", "jiling", "tianfeng", "mateng"],
	offline_piracyE_xk: ["xk_luoli", "xk_cuilian", "xk_penghu", "xk_shanfu", "xk_pengqi", "xk_zulang"],
	offline_piracyE_jb: ["pe_jun_caopi", "pe_jun_liushan", "pe_jun_sunquan", "pe_jun_liuxie", "pe_jun_liuhong", "pe_jun_liubei", "pe_jun_caocao", "pe_jun_sunce", "pe_jun_yuanshao", "pe_jun_zhangjiao"],
	offline_piracyE_hl: ["hl_shen_lvbu", "hl_shen_zhouyu", "hl_shen_lvmeng", "hl_shen_zhugeliang", "hl_shen_guanyu"],
	offline_piracyE: ["xia_caopi", "pe_xiahouxuan", "pe_guozhao", "pe_que", "yj_zhouji", "yj_ehuan", "yj_tianchuan", "yj_zhonghui", "yj_jiling", "yj_yongkai", "yj_chezhou", "yj_caocaoyuanshao"],
	offline_piracyS: ["ns_jiaxu", "longyufei", "ps_guanyu", "ps1059_guojia", "ps2070_guojia", "ps2063_zhaoyun", "ps2067_zhaoyun", "ps1062_zhouyu", "ps2080_zhouyu", "ps_caozhi", "ps_jin_simayi", "ps_caopi", "ps_simayi", "ps2068_simayi", "ps_machao", "ps_zhugeliang", "ps2066_zhugeliang", "ps_jiaxu", "ps_lvbu", "jsp_liubei"],
	offline_piracyK: ["pk_sp_duyu"],
	offline_vtuber: ["vtb_xiaosha", "vtb_xiaoshan", "vtb_xiaotao", "vtb_xiaole", "vtb_xiaojiu"],
	offline_huan: ["jun_lvbu"],
	offline_juedai: ["zj_huangchong", "zj_dingfeng", "zj_liaohua", "zj_zhugeliang", "zj_liuyuan", "zj_jiangwei", "zj_zhonghui", "xiahouhan", "zj_xiahouhan", "zj_yaokehui", "zj_huoyi", "zj_liuyin", "zj_zhugezhan", "zj_zhaotong", "zj_zhaoguang", "zj_lukang", "zj_zhugexu", "zj_hulie", "zj_zhanghu", "zj_yuechen"],
	offline_longyutao: ["drag_pangde", "drag_guanyu", "drag_caoren", "drag_lvchang"],
	offline_guansuo: ["drag_huaci", "drag_guansuo", "drag_guanyinping", "drag_guanping", "drag_zhoucang", "drag_liaohua", "drag_shendan", "drag_shenyi", "drag_luxun", "drag_xusheng", "she_lvmeng"],
	offline_taoyuan: ["ty_guanyu", "ty_sunquan", "ty_liubei", "ty_chenshi", "ty_chengjix", "ty_zhaorong", "ty_zhangnan", "ty_fengxí", "ty_liaohua", "ty_huangzhong", "ty_wuban", "ty_shicong", "ty_guanxing", "ty_shamoke", "ty_guanyinping", "ty_luxun", "ty_ganning", "ty_buzhi", "ty_tanxiong", "ty_liue", "ty_zhangda", "ty_fanjiang", "ty_anying", "ty_anyingx", "ty_wuque", "ty_yanque", "ty_wangque", "ty_shen_zhangfei", "ty_shen_guanyu", "ty_shen_liubei"],
	offline_hanmo: ["hm_bairao", "hm_guigu", "hm_bosi", "hm_nanhualaoxian", "hm_yudu", "hm_taosheng", "hm_fuyun", "hm_tangzhou", "hm_chengyuanzhi", "hm_gaosheng", "hm_heman", "hm_yanzheng", "hm_bocai", "hm_dengmao", "hm_shen_yl_luzhi", "hm_shen_huangfusong", "hm_shen_zhangjiao", "hm_shen_zhangbao", "hm_shen_zhangliang", "hm_shen_zhujun"],
	offline_jingxiang: ["jx_zhouyu", "jx_guanyu", "jx_shen_caoren", "jx_shen_liubiao"],
	offline_changan: ["ca_wangyun", "ca_lvbu", "ca_lijue", "ca_guosi", "ca_zhangji", "ca_fanchou", "ca_shen_wangyun", "ca_shen_caocao", "ca_shen_lijueguosi", "zombie_jiaxu", "zombie_zombie"],
	offline_weinan: ["wn_caocao", "wn_hansui", "wn_houxuan", "wn_chengyi", "wn_yangqiú", "wn_zhanghe", "wn_jiaxu", "wn_xuhuang", "wn_zhuling", "wn_shen_machao", "wn_shen_xuzhu"],
	offline_Europe: ["eu_kaisa", "eu_Macrinus", "eu_Ardashir", "eu_makang", "eu_yujin", "eu_zhangliao", "eu_yuejin"],
	offline_jiudin: ["jd_jin_wangyuanji", "jd_ol_huaxin", "jd_sp_yangwan", "jd_sb_huangyueying", "jd_sb_zhaoyun", "jd_sb_ganning", "jd_sb_pangtong", "jd_hanlong", "jd_jin_xiahouhui", "jd_jin_simazhao", "jd_sb_caocao", "jd_sb_sp_zhugeliang", "jd_simayan", "jd_sb_sunquan", "jd_sb_xiaoqiao", "jd_sb_guanyu", "jd_sb_jiangwei", "jd_sb_daqiao", "jd_sb_menghuo", "jd_sb_yuanshao", "jd_sb_yujin", "jd_sb_sunshangxiang", "jd_sb_liubei", "jd_sb_fazheng", "jd_sb_zhangfei", "jd_jin_simashi", "jd_sb_xuhuang"],
	offline_yanyou: ["yy_quyi", "yy_gongsunzan", "yy_wenchou", "yy_gongsunyuan", "yy_yuanshao", "yy_simayi", "yy_caorui", "yy_zhaoyun", "yy_quancong"],
	offline_jingyang: ["jy_caocao", "jy_caoren", "jy_zhugeliang", "jy_pangtong", "jy_lusu", "jy_zhangzhao", "jy_zhouyu", "jy_huanggai"],
	offline_shichangshi: ["ps_zhangrang", "ps_zhaozhong", "ps_sunzhang", "ps_bilan", "ps_xiayun", "ps_hankui", "ps_lisong", "ps_duangui", "ps_guosheng", "ps_gaowang"],
	offline_prettyDerby: ["sm_chixia", "sm_qiulin", "sm_zhuahuang", "sm_zijian", "sm_jieying", "sm_liaoyuan", "sm_dailu"],
	offline_qingshi: ["chenshou", "hs_liuxuan", "hs_caohuan", "hs_liuxie", "hs_sunhao"],
	offline_fengyun: ["ps_caocao", "ps_liubei", "ps_sunquan"],
	offline_xy: ["xy_caocao", "xy_chengyu", "xy_xunyu", "xy_chengong", "xy_zhangkai", "xy_lvbu", "xy_zhangmiao", "xy_caosong"],
	offline_zc26: ["zc26_sp_xushi", "zc26_lusu", "zc26_jiaxu", "zc26_zhanghe", "zc26_taishici"],
	offline_wenxindiaolong: ["wxdl_caozhi", "wxdl_caocao"],
	offline_shiningGrils: ["shinin_zhenji", "shinin_wuguotai", "shinin_ruiji", "shinin_lvlingqi", "shinin_dongwan", "goblin", "lord_goblin"],
	offline_yanling: ["ylyg_xiaoqiao", "ylyg_yuji", "ylyg_pangtong", "ylyg_dianwei", "ylyg_xuhuang", "ylyg_zhurong"],
	//offline_others: [],
};

const characterSortTranslate = {
	offline_hanmo: "风云志·汉末风云",
	offline_scl: "王者之战",
	offline_star: "桌游志·SP",
	offline_sticker: "桌游志·贴纸",
	offline_yijiang: "一将之魂",
	offline_luanwu: "文和乱武",
	offline_yongjian: "用间篇",
	offline_yongjian_prefix: "用间",
	offline_feihongyingxue: "飞鸿映雪",
	offline_piracyE_zy: "官盗E系列·战役篇",
	offline_piracyE_xk: "官盗E系列·侠客行",
	offline_piracyE_jb: "官盗E系列·君霸天下",
	offline_piracyE_hl: "官盗E系列·神霸虎牢",
	offline_piracyE: "官盗E系列",
	offline_piracyS: "官盗S系列",
	offline_vtuber: "天书乱斗·虚拟偶像",
	offline_huan: "三国杀·幻",
	offline_piracyK: "官盗K系列",
	offline_others: "线下其他系列",
	offline_juedai: "绝代智将",
	offline_longyutao: "山河煮酒·龙起襄樊",
	offline_jingxiang: "风云志·荆襄风云",
	offline_changan: "风云志·长安风云",
	offline_weinan: "风云志·渭南风云",
	offline_taoyuan: "山河煮酒·桃园挽歌",
	offline_guansuo: "山河煮酒·关索传",
	offline_jiudin: "九鼎系列",
	offline_yanyou: "燕幽烽火",
	offline_jingyang: "荆扬对垒",
	offline_qingshi: "特典·青史翰墨",
	offline_shichangshi: "蛇年限定·十常侍",
	offline_prettyDerby: "马年限定·赛马娘",
	offline_fengyun: "风云际会",
	offline_Europe: "风云志·欧陆风云",
	offline_xy: "徐兖纵横",
	offline_zc26: "26珍藏",
	offline_wenxindiaolong: "星汉灿烂·文心雕龙",
	offline_shiningGrils: "闪耀战姬",
	offline_yanling: "雁翎耀光",
	extra_offline: "神话再临·线下",
};

export { characterSort, characterSortTranslate };
