const characters = {
	//嗔
	sxrm_zhouyu: {
		sex: "male",
		group: "devil",
		hp: 4,
		skills: ["sxrmjiehuo", "sxrmxianger", "sxrmmieguo"],
		groupInGuozhan: "wu",
	},
	sxrm_sunshangxiang: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["sxrmjiaozong", "sxrmfusui"],
	},
	sxrm_zhangzhao: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["sxrmxiezhong", "sxrmqishi"],
	},
	sxrm_lusu: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["sxrmwanli", "sxrmlishui"],
	},
	sxrm_chen_caocao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["sxrmlanjiao"],
	},
	sxrm_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["sxrmbingqu", "sxrmfanxin"],
		groupBorder: "shen",
		names: "诸葛|亮",
		clans: ["琅琊诸葛氏"],
	},
	sxrm_jiahua: {
		sex: "male",
		group: "wu",
		hp: 5,
		skills: ["sxrmfubei", "sxrmdancui"],
	},
	sxrm_zhaoyun: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["sxrmzhaduo"],
	},
	sxrm_caoren: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["sxrmyangbei", "sxrmyinfeng"],
	},
	//慢
	sxrm_guanyu: {
		sex: "male",
		group: "devil",
		hp: 5,
		skills: ["sxrmhanguo", "sxrmweiwo"],
		groupInGuozhan: "shu",
	},
	sxrm_guanyinping: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["sxrmyinmou", "sxrmquchi"],
	},
	sxrm_yujin: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["sxrmsuwu", "sxrmrenwang"],
	},
	sxrm_mifang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["sxrmhuoe", "sxrmtanduo"],
	},
	sxrm_liufeng: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["sxrmhuaibing"],
		names: "刘|封",
	},
	sxrm_luxun: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["sxrmchanyu", "sxrmcongfeng"],
		clans: ["吴郡陆氏"],
	},
	sxrm_lvmeng: {
		sex: "male",
		group: "wu",
		hp: 3,
		maxHp: 4,
		skills: ["sxrmkongzhi", "sxrmbizha"],
	},
	sxrm_pangde: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["sxrmnuozhan"],
	},
	sxrm_yanwen: {
		sex: "male",
		group: "qun",
		hp: 5,
		skills: ["sxrmhaibian", "sxrmqiewang"],
		names: "颜|良-文|丑",
	},
	//疑
	sxrm_caocao: {
		sex: "male",
		group: "devil",
		hp: 3,
		skills: ["sxrmkuxin", "sxrmsigu"],
		groupInGuozhan: "wei",
	},
	sxrm_caopi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["sxrmzhengsi", "sxrmchengming"],
	},
	sxrm_wanghou: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["sxrmjugu"],
	},
	sxrm_liubei: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["sxrmchengbian"],
	},
	sxrm_jianggan: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["sxrmzongheng", "sxrmduibian"],
	},
	sxrm_huatuo: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["sxrmmiehai"],
	},
	sxrm_lvboshe: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["sxrmqingjun"],
	},
	sxrm_fuhuanghou: {
		sex: "female",
		group: "qun",
		hp: 3,
		maxHp: 4,
		skills: ["sxrmmitu", "sxrmqianliu"],
	},
	sxrm_xunyu: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["sxrmhuice", "sxrmyihe", "sxrmjizhi"],
		clans: ["颍川荀氏"],
	},
};

export default characters;
