const characters = {
	pot_xiahouba: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["potlibing", "potpoxi"],
		names: "夏侯|霸",
	},
	pot_chenqun: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["potfaen", "potdingpin"],
	},
	pot_caozhen: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["potsifeng"],
	},
	pot_lvyi: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["pothuilv", "potsongyan", "potshishi"],
	},
	pot_caoshuang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["potdianyi", "potshequan", "potjianzhuan"],
	},
	pot_zhangren: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["potfuan", "potyinxian"],
	},
	pot_sunchen: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["potnigu", "potlulian"],
	},
	zhuji: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["potjiezhu", "pothuanshi"],
	},
	sp_zhonghui: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["mbsizi", "mbxiezhi", "mbyunan", "mbkechang"],
		isZhugong: true,
		clans: ["颍川钟氏"],
		doubleGroup: ["wei", "qun"],
	},
	pot_zanghong: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["pot_liezhi", "pot_jugu"],
	},
	pot_chenjiao: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["potqingyan", "potceduan"],
	},
	pot_chendao: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["potwanglie", "pothongyi"],
	},
	pot_dengai: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["pottuntian", "potzaoxian", "potjixi"],
	},
	pot_huanjie: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["potgongmou", "potzhengshuo"],
	},
	pot_xinxianying: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["potjiejie", "potqingshi"],
	},
	mb_chenzhi: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["mbquanchong", "mbrenxing"],
	},
	pot_lusu: {
		sex: "male",
		hp: 3,
		group: "wu",
		skills: ["pothaoshi", "potdimeng"],
	},
	mb_sunjun: {
		sex: "male",
		hp: 3,
		group: "wu",
		skills: ["mbxiongtu", "mbxianshuai"],
	},
	pot_weiyan: {
		hp: 4,
		sex: "male",
		group: "shu",
		skills: ["potzhongao", "potzhuangshi", "potyinzhan"],
	},
	mb_zhangyan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["mbfeijing", "mbxiaoge"],
	},
	guoyuan: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["mbqingdao", "mbxiugeng", "mbchenshe"],
	},
	mb_huangzu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["mbchizhang", "mbduanyang"],
	},
	mb_tianfeng: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["mbganggeng", "mbsijian"],
	},
	mb_luyusheng: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["mbrunwei", "mbshuanghuai"],
		clans: ["吴郡陆氏"],
	},
	mb_yanghong: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["mbjianji", "mbyuanmo"],
	},
	mb_xiahoushang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["mbtanfeng"],
		dieAudios: ["tw_xiahoushang"],
		img: "image/character/tw_xiahoushang.jpg",
		names: "夏侯|尚",
	},
	sunsháo: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["mbganjue", "mbzhuji"],
	}, //跟孙邵拼音字母相同了
	pangxi: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["mbxuye", "mbkuangxiang"],
	},
	pot_yuji: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["potfuji", "potdaozhuan"],
	},
	pot_lougui: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["potguansha", "potjiyu"],
	},
	pot_dongzhao: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["spmiaolve", "spyingjia"],
		img: "image/character/tw_dongzhao.jpg",
		dieAudios: ["tw_dongzhao"],
	},
	pot_taishici: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["pothanzhan", "potzhanlie", "potzhenfeng"],
		names: "太史|慈",
	},
};

export default characters;
