const characterSort = {
	extra_mb: ["xin_simayi", "mb_shen_machao"],
	mobile_sp2: ["mb_sunluyu"],
	mobile_sp3: ["mb_guanyinping", "mb_caohong"],
	mobile_sp4: ["re_heqi", "mb_chengyu"],
	mobile_sp5: ["mb_dongbai"],
	mobile_sp6: ["dongcheng", "re_weiwenzhugezhi"],
	mobile_sp7: ["taoqian", "yangyi"],
	mobile_sp8: ["shenpei", "re_wangyun"],
	mobile_sp9: ["jiakui", "sp_sufei", "re_zhanggong", "re_xugong", "re_baosanniang"],
	mobile_sp10: ["furong", "zhouqun", "zhangyì", "dengzhi", "gongsunkang", "hucheer", "chendeng", "dingyuan"],
	mobile_sp11: ["mb_wutugu", "fuqian", "qiaozhou", "ruanhui", "sp_maojie", "wangjun", "yanpu", "mayuanyi", "xin_mamidi"],
	mobile_sp12: ["hujinding", "lifeng", "zhaotongzhaoguang", "wangyuanji", "yanghuiyu", "liuye", "simazhao", "zhuling", "yangbiao"],
	mobile_sp13: ["sp_caosong", "sp_pengyang", "liwei", "xin_guozhao", "qianzhao", "peixiu", "yanxiang", "xin_hansui", "yangfu"],
	mobile_sp14: ["mb_ganfuren", "xin_huojun", "laimin", "xin_wuban", "mb_huban", "sp_jianggan", "baoxin", "mb_chengui", "muludawang", "yangfeng"],
	mobile_sp15: ["mb_mengda", "mb_qinghegongzhu", "mb_wangjing", "mb_sp_zhenji", "jiangji", "zhangbu", "wuke", "mb_caocao", "mb_zerong"],
	mobile_sp_default: ["mb_gaoxiang", "mb_cuimao", "mb_tw_zhangji", "hanxuan", "mb_xianglang", "mb_xingdaorong", "mb_dingshangwan"],
	mobile_xlqk1: ["lingcao", "sunru", "liuzan"],
	mobile_xlqk2: ["pangdegong", "miheng"],
	mobile_xlqk3: ["majun", "zhengxuan", "simashi"],
	mobile_xlqk4: ["nanhualaoxian", "shichangshi", "sunhanhua"],
	mobile_xlqk5: ["mb_zhangfen", "mb_cuilingyi"],
	mobile_xlqk6: ["mb_caoxing", "mb_luyu", "mb_zhangzhi", "mb_caozhi", "mb_zhouyu", "mb_liuhui"],
	mobile_longxue: ["mb_simazhao", "mb_simafu", "mb_wenqin", "mb_simazhou", "mb_sp_guanqiujian", "mb_caomao", "chengji", "lizhaojiaobo", "mb_jiachong"],
	mobile_laoyouji: ["friend_zhugeliang", "friend_xushu", "friend_pangtong", "friend_cuijun", "friend_shitao"],
	mobile_laoyouji_hefei: ["hefei_zhangliao", "hefei_lidian", "hefei_yuejin"],
	mobile_standard: ["xin_xiahoudun", "xin_zhangfei", "old_yuanshu"],
	mobile_shenhua_feng: ["re_xiaoqiao", "xin_zhoutai"],
	mobile_shenhua_huo: ["re_pangtong", "re_sp_zhugeliang", "re_xunyu", "re_dianwei", "re_yanwen", "xin_yuanshao"],
	mobile_shenhua_lin: ["re_dongzhuo", "re_sunjian", "re_zhurong"],
	mobile_shenhua_shan: ["re_liushan", "re_dengai", "re_jiangwei", "re_caiwenji", "re_zhangzhang", "re_sunben"],
	mobile_shenhua_yin: ["xin_sunliang", "re_yanyan", "re_wangji"],
	mobile_shenhua_lei: ["re_guanqiujian", "re_zhoufei"],
	mobile_yijiang1: ["re_xusheng", "re_lingtong", "ol_yujin", "re_wuguotai", "re_gaoshun", "re_caozhi"],
	mobile_yijiang2: ["xin_liaohua", "xin_caozhang", "re_liubiao", "re_handang", "xin_chengpu", "xin_gongsunzan", "re_zhonghui", "re_bulianshi"],
	mobile_yijiang3: ["re_liru", "xin_jianyong", "xin_zhuran", "xin_guohuai", "xin_panzhangmazhong", "xin_fuhuanghou", "re_yufan"],
	mobile_yijiang4: ["xin_zhoucang", "xin_caifuren", "xin_guyong", "xin_sunluban", "xin_caozhen", "xin_jushou", "xin_wuyi", "xin_zhuhuan", "re_chenqun"],
	mobile_yijiang5: ["xin_zhangyi", "xin_sunxiu", "xin_quancong", "xin_zhuzhi", "xin_caoxiu", "mb_zhongyao"],
	mobile_yijiang7: ["re_jikang", "mb_xuezong"],
	mobile_changshi: ["scs_zhangrang", "scs_zhaozhong", "scs_sunzhang", "scs_bilan", "scs_xiayun", "scs_hankui", "scs_lisong", "scs_duangui", "scs_guosheng", "scs_gaowang"],
	mobile_yuan: ["o_sunquan", "o_tanshihuai", "o_lvbu", "o_gaoshun", "o_guanyu", "o_meicheng", "o_chenlan", "o_tadun"],
	mobile_others: [],
};

const characterSortTranslate = {
	mobile_standard: "手杀异构·标准包",
	mobile_shenhua_feng: "手杀异构·其疾如风",
	mobile_shenhua_huo: "手杀异构·侵掠如火",
	mobile_shenhua_lin: "手杀异构·其徐如林",
	mobile_shenhua_shan: "手杀异构·不动如山",
	mobile_shenhua_yin: "手杀异构·难知如阴",
	mobile_shenhua_lei: "手杀异构·动如雷霆",
	mobile_yijiang1: "手杀异构·将1",
	mobile_yijiang2: "手杀异构·将2",
	mobile_yijiang3: "手杀异构·将3",
	mobile_yijiang4: "手杀异构·将4",
	mobile_yijiang5: "手杀异构·将5",
	mobile_yijiang7: "手杀异构·原7",
	mobile_sp2: "SP·组2",
	mobile_sp3: "SP·组3",
	mobile_sp4: "SP·组4",
	mobile_sp5: "SP·组5",
	mobile_sp6: "SP·组6",
	mobile_sp7: "SP·组7",
	mobile_sp8: "SP·组8",
	mobile_sp9: "SP·组9",
	mobile_sp10: "SP·组10",
	mobile_sp11: "SP·组11",
	mobile_sp12: "SP·组12",
	mobile_sp13: "SP·组13",
	mobile_sp14: "SP·组14",
	mobile_sp15: "SP·组15",
	mobile_sp_default: "SP·未分组",
	mobile_xlqk1: "袖里乾坤·组1",
	mobile_xlqk2: "袖里乾坤·组2",
	mobile_xlqk3: "袖里乾坤·组3",
	mobile_xlqk4: "袖里乾坤·组4",
	mobile_xlqk5: "袖里乾坤·组5",
	mobile_xlqk6: "袖里乾坤·君子六艺",
	mobile_longxue: "龙血玄黄",
	mobile_laoyouji: "老友季",
	mobile_laoyouji_hefei: "千里之骥",
	mobile_yuan: "移动版·缘",
	mobile_others: "其他",
	mobile_changshi: "十常侍单体",
	extra_mb: "神将异构·移动版",
};

export { characterSort, characterSortTranslate };
