const characters = {
	ol_quancong: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["olyaoming"],
	},
	ol_caoxiu: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["olqianju", "olqingxi"],
	},
	ol_guanping: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["longyin", "oljieyong"],
	},
	dm_zhangfei: {
		sex: "male",
		group: "shu",
		hp: 5,
		skills: ["olzhuohun", "olchenshi"],
	},
	ol_xiahoushi: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["olqiaoshi", "olyanyu"],
	},
	junk_zhangjiao: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["yizhao", "junksijun", "tianjie"],
		groupInGuozhan: "qun",
		dieAudios: ["shen_zhangjiao"],
	},
	shen_sunquan: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["junkyuheng", "junkdili"],
		groupInGuozhan: "wu",
	},
	shen_dianwei: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["juanjia", "qiexie", "cuijue"],
		groupInGuozhan: "wei",
	},
	ol_zhangliao: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["olduorui", "olzhiti"],
		groupInGuozhan: "wei",
		dieAudios: ["shen_zhangliao"],
	},
	shen_caopi: {
		sex: "male",
		group: "shen",
		hp: 5,
		skills: ["chuyuan", "dengji"],
		groupInGuozhan: "wei",
	},
	shen_zhenji: {
		sex: "female",
		group: "shen",
		hp: 3,
		skills: ["shenfu", "qixian"],
		groupInGuozhan: "wei",
	},
	ol_zhangsong: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["olqiangzhi", "olxiantu"],
	},
	ol_jsrg_zhanghe: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olqiongtu", "olxianzhu"],
		doubleGroup: ["wei", "qun"],
		dieAudios: ["jsrg_zhanghe"],
	},
	ol_caojie: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["olshouxi", "olhuimin"],
	},
	ol_re_xinxianying: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["olcaishi", "olzhongjian"],
	},
	ol_sb_dongzhao: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["olsbshunji", "olsbyishi"],
	},
	ol_sb_chengyu: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["olsbliduan", "olsbdanchi"],
	},
	dm_caocao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["olbachao", "olfuzai"],
	},
	ol_sb_xizhicai: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["olsbxinchuan", "olsbjinjin"],
	},
	dm_sunquan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["olquanyu", "oltianen", "olqiangang"],
	},
	ol_sb_guojia: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["olsbdinglun", "olsbjieli"],
	},
	ol_re_yujin: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["ol_zhenjun", "ol_yizhong"],
	},
	ol_jsrg_zhujun: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olfendi", "oljuxiang"],
	},
	ol_jsrg_sunjian: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olpingtao", "oljuelie"],
		img: "image/character/jsrg_sunjian.jpg",
	},
	ol_jsrg_zhangliao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olzhengbing", "jsrgtuwei"],
		doubleGroup: ["wei", "qun"],
		dieAudios: ["jsrg_zhangliao"],
	},
	ol_sb_xuyou: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["olsbqianfu", "olsbyushi", "olsbfenchao"],
	},
	ol_sb_lusu: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["olsbduduan", "olsbyinglve", "olsbmengshi"],
	},
	ol_sb_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["olsbzhitian", "olsbwujing", "olsbzhijue"],
		names: "诸葛|亮",
	},
	ol_sunluban: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["olzenhui", "oljiaojin"],
	},
	dm_lvbu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olduoqi", "olkuangmo", "olgangquan"],
	},
	dm_diaochan: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["olhuanhuo", "olqingshi"],
		names: "null|null",
	},
	ol_guohuanghou: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["oljiaozhao", "oldanxin"],
		names: "郭|null",
	},
	ol_sb_xiaoqiao: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["olmiluo", "oljueyan"],
		names: "桥|null",
	},
	dm_simayi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["olguifu", "olmoubian"], //,"olzhouxi"
		name: "司马|懿",
	},
	ol_madai: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["mashu", "olqianxi"],
	},
	ol_sb_yl_luzhi: {
		sex: "male",
		group: "qun",
		hp: 3,
		maxHp: 4,
		skills: ["olsibing", "olliance"],
	},
	ol_guanzhang: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["olfuhun"],
		names: "关|兴-张|苞",
	},
	ol_jsrg_liuhong: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olchaozheng", "olshenchong", "oljulian"],
		isZhugong: true,
		img: "image/character/jsrg_liuhong.jpg",
		dieAudios: ["jsrg_liuhong"],
	},
	ol_jsrg_zhaoyun: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["ollonglin", "olzhendan"],
		img: "image/character/jsrg_zhaoyun.jpg",
		dieAudios: ["jsrg_zhaoyun"],
	},
	ol_sb_jiaxu: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["olsbwance", "olsbchenzhi", "olsbluanchao"],
	},
	ol_sb_wenchou: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olsblunzhan", "olsbjuejue"],
	},
	ol_sb_zhangrang: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["olsblucun", "olsbtuisheng"],
		trashBin: ["sex:male_castrated"],
		dieAudios: ["3"],
	},
	ol_fuhuanghou: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["rezhuikong", "olqiuyuan"],
	},
	ol_guohuai: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["oljingce"],
	},
	ol_sunxiu: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["reyanzhu", "rexingxue", "xinzhaofu"],
		isZhugong: true,
	},
	ol_sb_zhangxiu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olsbchoulie", "olsbzhuijiao"],
	},
	ol_sb_zhaoyun: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["olsbnilan", "olsbjueya"],
	},
	ol_sb_zhangfei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["olsbjingxian", "olsbxieyong"],
	},
	ol_sb_huangyueying: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["olsblixian", "olsbbingcai"],
	},
	ol_sb_jushou: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["olsbguliang", "olsbxutu"],
	},
	ol_sb_gongsunzan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olsbjiaodi", "olsbbaojing"],
		names: "公孙|瓒",
	},
	ol_sb_dengai: {
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 5,
		skills: ["olsbjigu", "olsbjiewan"],
	},
	ol_sb_dongzhuo: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olguanbian", "olxiongni", "olfengshang", "olzhibin"],
		isZhugong: true,
		dieAudios: ["3"],
	},
	ol_sb_huaxiong: {
		sex: "male",
		group: "qun",
		hp: 6,
		skills: ["olsbbojue", "olsbyangwei"],
	},
	ol_sb_yuanshu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olsbjinming", "olsbxiaoshi", "olsbyanliang"],
		isZhugong: true,
	},
	ol_sb_sunjian: {
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 5,
		skills: ["olsbhulie", "olsbyipo"],
	},
	ol_sb_jiangwei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["olsbzhuri", "olsbranji"],
	},
	ol_caozhang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["oljiangchi"],
		dieAudios: ["xin_caozhang"],
	},
	ol_jianyong: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["olqiaoshui", "jyzongshi"],
		tempname: ["re_jianyong"],
		dieAudios: ["re_jianyong"],
	},
	ol_lingtong: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["olxuanfeng"],
		tempname: ["re_lingtong"],
		dieAudios: ["re_lingtong"],
	},
	ol_sb_guanyu: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["olsbweilin", "olsbduoshou"],
	},
	ol_sb_taishici: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["olsbdulie", "olsbdouchan"],
		names: "太史|慈",
	},
	ol_gaoshun: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olxianzhen", "decadejinjiu"],
		dieAudios: ["re_gaoshun"],
	},
	ol_sb_yuanshao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olsbhetao", "olsbshenli", "olsbyufeng", "olsbshishou"],
		dieAudios: ["2"],
		isZhugong: true,
	},
	ol_yufan: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["olzongxuan", "olzhiyan"],
	},
	ol_chengpu: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["dclihuo", "olchunlao"],
		tempname: ["xin_chengpu"],
		dieAudios: ["xin_chengpu"],
	},
	ol_wangyi: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["olzhenlie", "olmiji"],
	},
	ol_sb_pangtong: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["olsbhongtu", "olsbqiwu"],
		dieAudios: ["3"],
	},
	ol_fazheng: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["olxuanhuo", "olenyuan"],
	},
	ol_caifuren: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["olqieting", "xianzhou"],
		names: "蔡|null",
	},
	ol_liru: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["oljuece", "olmieji", "dcfencheng"],
	},
	ol_liubiao: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["olzishou", "olzongshi"],
	},
	ol_wuguotai: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["olganlu", "olbuyi"],
		names: "丁|null",
	},
	ol_sb_kongrong: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["olsbliwen", "olsbzhengyi"],
	},
	ol_zhangchunhua: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["jueqing", "shangshi", "oljianmie"],
	},
	ol_caochong: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["olchengxiang", "olrenxin"],
	},
	ol_caozhi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["reluoying", "oljiushi"],
	},
	ol_liaohua: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["oldangxian", "olfuli"],
	},
};

export default characters;
