const characterSort = {
	extra_ol: ["shen_dianwei", "ol_zhangliao", "shen_caopi", "shen_zhenji", "shen_sunquan", "junk_zhangjiao"],
	onlyOL_yijiang1: ["ol_zhangchunhua", "ol_lingtong", "ol_gaoshun", "ol_fazheng", "ol_wuguotai", "ol_caozhi", "ol_re_yujin"],
	onlyOL_yijiang2: ["ol_liaohua", "ol_caozhang", "ol_chengpu", "ol_wangyi", "ol_liubiao", "ol_guanzhang", "ol_madai"],
	onlyOL_yijiang3: ["ol_jianyong", "ol_guohuai", "ol_fuhuanghou", "ol_yufan", "ol_liru", "ol_caochong", "ol_guanping"],
	onlyOL_yijiang4: ["ol_zhangsong", "ol_caifuren", "ol_sunluban"],
	onlyOL_yijiang5: ["ol_xiahoushi", "ol_sunxiu", "ol_quancong"],
	onlyOL_yijiang6: ["ol_guohuanghou"],
	onlyOL_yijiang7: ["ol_caojie", "ol_re_xinxianying", "ol_caoxiu"],
	onlyOL_ol_jsrg: ["ol_jsrg_zhanghe", "ol_jsrg_zhaoyun", "ol_jsrg_liuhong", "ol_jsrg_zhangliao", "ol_jsrg_zhujun", "ol_jsrg_sunjian"],
	onlyOL_sb_mouding: ["ol_sb_lusu", "ol_sb_zhugeliang", "ol_sb_jiangwei", "ol_sb_pangtong", "ol_sb_jiaxu", "ol_sb_guojia"],
	onlyOL_sb_wudong: ["ol_sb_zhaoyun", "ol_sb_zhangfei", "ol_sb_guanyu", "ol_sb_dongzhuo"],
	onlyOL_sb_fenwu: ["ol_sb_gongsunzan", "ol_sb_zhangxiu", "ol_sb_dengai", "ol_sb_taishici", "ol_sb_yuanshao", "ol_sb_sunjian", "ol_sb_huaxiong", "ol_sb_wenchou"],
	onlyOL_sb_shiren: ["ol_sb_kongrong", "ol_sb_yl_luzhi"],
	onlyOL_sb_daquan: ["ol_sb_dongzhao", "ol_sb_xuyou", "ol_sb_jushou", "ol_sb_yuanshu", "ol_sb_zhangrang"],
	onlyOL_sb_jichu: ["ol_sb_chengyu", "ol_sb_xizhicai"],
	onlyOL_sb_huahao: ["ol_sb_xiaoqiao", "ol_sb_huangyueying"],
	onlyOL_demonized: ["dm_simayi", "dm_diaochan", "dm_lvbu", "dm_sunquan", "dm_caocao", "dm_zhangfei"],
	onlyOL_waitingforsort: [],
};

const characterSortTranslate = {
	onlyOL_yijiang1: "OL专属·将1",
	onlyOL_yijiang2: "OL专属·将2",
	onlyOL_yijiang3: "OL专属·将3",
	onlyOL_yijiang4: "OL专属·将4",
	onlyOL_yijiang5: "OL专属·将5",
	onlyOL_yijiang6: "OL专属·原6",
	onlyOL_yijiang7: "OL专属·原7",
	onlyOL_ol_jsrg: "闪耀星河·江山如故",
	onlyOL_sb_mouding: "上兵伐谋·谋定天下",
	onlyOL_sb_wudong: "上兵伐谋·武动乾坤",
	onlyOL_sb_fenwu: "上兵伐谋·奋勇扬威",
	onlyOL_sb_shiren: "上兵伐谋·施仁布德",
	onlyOL_sb_daquan: "上兵伐谋·达权通变",
	onlyOL_sb_jichu: "上兵伐谋·计出万全",
	onlyOL_sb_huahao: "上兵伐谋·花好月圆",
	onlyOL_demonized: "OL·魔",
	onlyOL_waitingforsort: "等待分包",
	extra_ol: "神将异构·OL",
};

export { characterSort, characterSortTranslate };
